[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]


[phases.setup]
nixPkgs = ["nodejs", "php", "composer"]

[phases.build]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm install",
  "npm run prod"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

